server.port=8080
spring.application.name=raft-exchange
eureka.client.serviceUrl.defaultZone=https://upex-cloud-eureka-qa.glb.osl-nucleus.io/eureka
eureka.client.registryFetchIntervalSeconds=5
eureka.client.instanceInfoReplicationIntervalSeconds=5
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=${spring.cloud.client.ip-address}
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${server.port}
eureka.instance.status-page-url=http://${eureka.instance.ip-address}:${management.server.port}/info
eureka.instance.health-check-url=http://${eureka.instance.ip-address}:${management.server.port}/health

server.tomcat.threads.max=25
server.tomcat.threads.min-spare=25


raftexchange.kafka.spot.bootstrap.servers=b-1.qabusinessmsk.rtlikw.c4.kafka.ap-northeast-1.amazonaws.com:9092,b-2.qabusinessmsk.rtlikw.c4.kafka.ap-northeast-1.amazonaws.com:9092,b-3.qabusinessmsk.rtlikw.c4.kafka.ap-northeast-1.amazonaws.com:9092
raftexchange.kafka.spot.topic=raftexchange-trade-event
raftexchange.kafka.perp.bootstrap.servers=b-1.qabusinessmsk.rtlikw.c4.kafka.ap-northeast-1.amazonaws.com:9092,b-2.qabusinessmsk.rtlikw.c4.kafka.ap-northeast-1.amazonaws.com:9092,b-3.qabusinessmsk.rtlikw.c4.kafka.ap-northeast-1.amazonaws.com:9092
raftexchange.kafka.perp.topic=raftexchange-trade-event
raftexchange.kafka.delivery.bootstrap.servers=b-1.qabusinessmsk.rtlikw.c4.kafka.ap-northeast-1.amazonaws.com:9092,b-2.qabusinessmsk.rtlikw.c4.kafka.ap-northeast-1.amazonaws.com:9092,b-3.qabusinessmsk.rtlikw.c4.kafka.ap-northeast-1.amazonaws.com:9092
raftexchange.kafka.delivery.topic=raftexchange-trade-event
raftexchange.kafka.fund.bootstrap.servers=b-1.qabusinessmsk.rtlikw.c4.kafka.ap-northeast-1.amazonaws.com:9092,b-2.qabusinessmsk.rtlikw.c4.kafka.ap-northeast-1.amazonaws.com:9092,b-3.qabusinessmsk.rtlikw.c4.kafka.ap-northeast-1.amazonaws.com:9092
raftexchange.kafka.fund.topic=raftexchange-fund-event
raftexchange.kafka.other.bootstrap.servers=b-1.qabusinessmsk.rtlikw.c4.kafka.ap-northeast-1.amazonaws.com:9092,b-2.qabusinessmsk.rtlikw.c4.kafka.ap-northeast-1.amazonaws.com:9092,b-3.qabusinessmsk.rtlikw.c4.kafka.ap-northeast-1.amazonaws.com:9092
raftexchange.kafka.other.topic=raftexchange-market-data


management.server.port=28081
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health,info,raft,metrics,prometheus
