// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Usuario.proto

package com.binance.raftexchange.client.stubs.usuario;

public interface UsuariosOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Usuarios)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Usuario usuario = 1;</code>
   */
  java.util.List<com.binance.raftexchange.client.stubs.usuario.Usuario> 
      getUsuarioList();
  /**
   * <code>repeated .Usuario usuario = 1;</code>
   */
  com.binance.raftexchange.client.stubs.usuario.Usuario getUsuario(int index);
  /**
   * <code>repeated .Usuario usuario = 1;</code>
   */
  int getUsuarioCount();
  /**
   * <code>repeated .Usuario usuario = 1;</code>
   */
  java.util.List<? extends com.binance.raftexchange.client.stubs.usuario.UsuarioOrBuilder> 
      getUsuarioOrBuilderList();
  /**
   * <code>repeated .Usuario usuario = 1;</code>
   */
  com.binance.raftexchange.client.stubs.usuario.UsuarioOrBuilder getUsuarioOrBuilder(
      int index);
}
