// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Usuario.proto

package com.binance.raftexchange.client.stubs.usuario;

/**
 * Protobuf type {@code Usuarios}
 */
public final class Usuarios extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Usuarios)
    UsuariosOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Usuarios.newBuilder() to construct.
  private Usuarios(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Usuarios() {
    usuario_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Usuarios();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Usuarios(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              usuario_ = new java.util.ArrayList<com.binance.raftexchange.client.stubs.usuario.Usuario>();
              mutable_bitField0_ |= 0x00000001;
            }
            usuario_.add(
                input.readMessage(com.binance.raftexchange.client.stubs.usuario.Usuario.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        usuario_ = java.util.Collections.unmodifiableList(usuario_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.binance.raftexchange.client.stubs.usuario.UsuarioProtos.internal_static_Usuarios_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.binance.raftexchange.client.stubs.usuario.UsuarioProtos.internal_static_Usuarios_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.binance.raftexchange.client.stubs.usuario.Usuarios.class, com.binance.raftexchange.client.stubs.usuario.Usuarios.Builder.class);
  }

  public static final int USUARIO_FIELD_NUMBER = 1;
  private java.util.List<com.binance.raftexchange.client.stubs.usuario.Usuario> usuario_;
  /**
   * <code>repeated .Usuario usuario = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.binance.raftexchange.client.stubs.usuario.Usuario> getUsuarioList() {
    return usuario_;
  }
  /**
   * <code>repeated .Usuario usuario = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.binance.raftexchange.client.stubs.usuario.UsuarioOrBuilder> 
      getUsuarioOrBuilderList() {
    return usuario_;
  }
  /**
   * <code>repeated .Usuario usuario = 1;</code>
   */
  @java.lang.Override
  public int getUsuarioCount() {
    return usuario_.size();
  }
  /**
   * <code>repeated .Usuario usuario = 1;</code>
   */
  @java.lang.Override
  public com.binance.raftexchange.client.stubs.usuario.Usuario getUsuario(int index) {
    return usuario_.get(index);
  }
  /**
   * <code>repeated .Usuario usuario = 1;</code>
   */
  @java.lang.Override
  public com.binance.raftexchange.client.stubs.usuario.UsuarioOrBuilder getUsuarioOrBuilder(
      int index) {
    return usuario_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < usuario_.size(); i++) {
      output.writeMessage(1, usuario_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < usuario_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, usuario_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.binance.raftexchange.client.stubs.usuario.Usuarios)) {
      return super.equals(obj);
    }
    com.binance.raftexchange.client.stubs.usuario.Usuarios other = (com.binance.raftexchange.client.stubs.usuario.Usuarios) obj;

    if (!getUsuarioList()
        .equals(other.getUsuarioList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUsuarioCount() > 0) {
      hash = (37 * hash) + USUARIO_FIELD_NUMBER;
      hash = (53 * hash) + getUsuarioList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.binance.raftexchange.client.stubs.usuario.Usuarios parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.binance.raftexchange.client.stubs.usuario.Usuarios parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.binance.raftexchange.client.stubs.usuario.Usuarios parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.binance.raftexchange.client.stubs.usuario.Usuarios parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.binance.raftexchange.client.stubs.usuario.Usuarios parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.binance.raftexchange.client.stubs.usuario.Usuarios parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.binance.raftexchange.client.stubs.usuario.Usuarios parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.binance.raftexchange.client.stubs.usuario.Usuarios parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.binance.raftexchange.client.stubs.usuario.Usuarios parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.binance.raftexchange.client.stubs.usuario.Usuarios parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.binance.raftexchange.client.stubs.usuario.Usuarios parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.binance.raftexchange.client.stubs.usuario.Usuarios parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.binance.raftexchange.client.stubs.usuario.Usuarios prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Usuarios}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Usuarios)
      com.binance.raftexchange.client.stubs.usuario.UsuariosOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.binance.raftexchange.client.stubs.usuario.UsuarioProtos.internal_static_Usuarios_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.binance.raftexchange.client.stubs.usuario.UsuarioProtos.internal_static_Usuarios_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.binance.raftexchange.client.stubs.usuario.Usuarios.class, com.binance.raftexchange.client.stubs.usuario.Usuarios.Builder.class);
    }

    // Construct using com.binance.raftexchange.client.stubs.usuario.Usuarios.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUsuarioFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (usuarioBuilder_ == null) {
        usuario_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        usuarioBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.binance.raftexchange.client.stubs.usuario.UsuarioProtos.internal_static_Usuarios_descriptor;
    }

    @java.lang.Override
    public com.binance.raftexchange.client.stubs.usuario.Usuarios getDefaultInstanceForType() {
      return com.binance.raftexchange.client.stubs.usuario.Usuarios.getDefaultInstance();
    }

    @java.lang.Override
    public com.binance.raftexchange.client.stubs.usuario.Usuarios build() {
      com.binance.raftexchange.client.stubs.usuario.Usuarios result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.binance.raftexchange.client.stubs.usuario.Usuarios buildPartial() {
      com.binance.raftexchange.client.stubs.usuario.Usuarios result = new com.binance.raftexchange.client.stubs.usuario.Usuarios(this);
      int from_bitField0_ = bitField0_;
      if (usuarioBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          usuario_ = java.util.Collections.unmodifiableList(usuario_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.usuario_ = usuario_;
      } else {
        result.usuario_ = usuarioBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.binance.raftexchange.client.stubs.usuario.Usuarios) {
        return mergeFrom((com.binance.raftexchange.client.stubs.usuario.Usuarios)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.binance.raftexchange.client.stubs.usuario.Usuarios other) {
      if (other == com.binance.raftexchange.client.stubs.usuario.Usuarios.getDefaultInstance()) return this;
      if (usuarioBuilder_ == null) {
        if (!other.usuario_.isEmpty()) {
          if (usuario_.isEmpty()) {
            usuario_ = other.usuario_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUsuarioIsMutable();
            usuario_.addAll(other.usuario_);
          }
          onChanged();
        }
      } else {
        if (!other.usuario_.isEmpty()) {
          if (usuarioBuilder_.isEmpty()) {
            usuarioBuilder_.dispose();
            usuarioBuilder_ = null;
            usuario_ = other.usuario_;
            bitField0_ = (bitField0_ & ~0x00000001);
            usuarioBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUsuarioFieldBuilder() : null;
          } else {
            usuarioBuilder_.addAllMessages(other.usuario_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.binance.raftexchange.client.stubs.usuario.Usuarios parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.binance.raftexchange.client.stubs.usuario.Usuarios) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.binance.raftexchange.client.stubs.usuario.Usuario> usuario_ =
      java.util.Collections.emptyList();
    private void ensureUsuarioIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        usuario_ = new java.util.ArrayList<com.binance.raftexchange.client.stubs.usuario.Usuario>(usuario_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.binance.raftexchange.client.stubs.usuario.Usuario, com.binance.raftexchange.client.stubs.usuario.Usuario.Builder, com.binance.raftexchange.client.stubs.usuario.UsuarioOrBuilder> usuarioBuilder_;

    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public java.util.List<com.binance.raftexchange.client.stubs.usuario.Usuario> getUsuarioList() {
      if (usuarioBuilder_ == null) {
        return java.util.Collections.unmodifiableList(usuario_);
      } else {
        return usuarioBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public int getUsuarioCount() {
      if (usuarioBuilder_ == null) {
        return usuario_.size();
      } else {
        return usuarioBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public com.binance.raftexchange.client.stubs.usuario.Usuario getUsuario(int index) {
      if (usuarioBuilder_ == null) {
        return usuario_.get(index);
      } else {
        return usuarioBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public Builder setUsuario(
        int index, com.binance.raftexchange.client.stubs.usuario.Usuario value) {
      if (usuarioBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsuarioIsMutable();
        usuario_.set(index, value);
        onChanged();
      } else {
        usuarioBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public Builder setUsuario(
        int index, com.binance.raftexchange.client.stubs.usuario.Usuario.Builder builderForValue) {
      if (usuarioBuilder_ == null) {
        ensureUsuarioIsMutable();
        usuario_.set(index, builderForValue.build());
        onChanged();
      } else {
        usuarioBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public Builder addUsuario(com.binance.raftexchange.client.stubs.usuario.Usuario value) {
      if (usuarioBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsuarioIsMutable();
        usuario_.add(value);
        onChanged();
      } else {
        usuarioBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public Builder addUsuario(
        int index, com.binance.raftexchange.client.stubs.usuario.Usuario value) {
      if (usuarioBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsuarioIsMutable();
        usuario_.add(index, value);
        onChanged();
      } else {
        usuarioBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public Builder addUsuario(
        com.binance.raftexchange.client.stubs.usuario.Usuario.Builder builderForValue) {
      if (usuarioBuilder_ == null) {
        ensureUsuarioIsMutable();
        usuario_.add(builderForValue.build());
        onChanged();
      } else {
        usuarioBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public Builder addUsuario(
        int index, com.binance.raftexchange.client.stubs.usuario.Usuario.Builder builderForValue) {
      if (usuarioBuilder_ == null) {
        ensureUsuarioIsMutable();
        usuario_.add(index, builderForValue.build());
        onChanged();
      } else {
        usuarioBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public Builder addAllUsuario(
        java.lang.Iterable<? extends com.binance.raftexchange.client.stubs.usuario.Usuario> values) {
      if (usuarioBuilder_ == null) {
        ensureUsuarioIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, usuario_);
        onChanged();
      } else {
        usuarioBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public Builder clearUsuario() {
      if (usuarioBuilder_ == null) {
        usuario_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        usuarioBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public Builder removeUsuario(int index) {
      if (usuarioBuilder_ == null) {
        ensureUsuarioIsMutable();
        usuario_.remove(index);
        onChanged();
      } else {
        usuarioBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public com.binance.raftexchange.client.stubs.usuario.Usuario.Builder getUsuarioBuilder(
        int index) {
      return getUsuarioFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public com.binance.raftexchange.client.stubs.usuario.UsuarioOrBuilder getUsuarioOrBuilder(
        int index) {
      if (usuarioBuilder_ == null) {
        return usuario_.get(index);  } else {
        return usuarioBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public java.util.List<? extends com.binance.raftexchange.client.stubs.usuario.UsuarioOrBuilder> 
         getUsuarioOrBuilderList() {
      if (usuarioBuilder_ != null) {
        return usuarioBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(usuario_);
      }
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public com.binance.raftexchange.client.stubs.usuario.Usuario.Builder addUsuarioBuilder() {
      return getUsuarioFieldBuilder().addBuilder(
          com.binance.raftexchange.client.stubs.usuario.Usuario.getDefaultInstance());
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public com.binance.raftexchange.client.stubs.usuario.Usuario.Builder addUsuarioBuilder(
        int index) {
      return getUsuarioFieldBuilder().addBuilder(
          index, com.binance.raftexchange.client.stubs.usuario.Usuario.getDefaultInstance());
    }
    /**
     * <code>repeated .Usuario usuario = 1;</code>
     */
    public java.util.List<com.binance.raftexchange.client.stubs.usuario.Usuario.Builder> 
         getUsuarioBuilderList() {
      return getUsuarioFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.binance.raftexchange.client.stubs.usuario.Usuario, com.binance.raftexchange.client.stubs.usuario.Usuario.Builder, com.binance.raftexchange.client.stubs.usuario.UsuarioOrBuilder> 
        getUsuarioFieldBuilder() {
      if (usuarioBuilder_ == null) {
        usuarioBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.binance.raftexchange.client.stubs.usuario.Usuario, com.binance.raftexchange.client.stubs.usuario.Usuario.Builder, com.binance.raftexchange.client.stubs.usuario.UsuarioOrBuilder>(
                usuario_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        usuario_ = null;
      }
      return usuarioBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Usuarios)
  }

  // @@protoc_insertion_point(class_scope:Usuarios)
  private static final com.binance.raftexchange.client.stubs.usuario.Usuarios DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.binance.raftexchange.client.stubs.usuario.Usuarios();
  }

  public static com.binance.raftexchange.client.stubs.usuario.Usuarios getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Usuarios>
      PARSER = new com.google.protobuf.AbstractParser<Usuarios>() {
    @java.lang.Override
    public Usuarios parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Usuarios(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Usuarios> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Usuarios> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.binance.raftexchange.client.stubs.usuario.Usuarios getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

