// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Usuario.proto

package com.binance.raftexchange.client.stubs.usuario;

public interface UsuarioOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Usuario)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fullname = 1;</code>
   * @return The fullname.
   */
  java.lang.String getFullname();
  /**
   * <code>string fullname = 1;</code>
   * @return The bytes for fullname.
   */
  com.google.protobuf.ByteString
      getFullnameBytes();

  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
